import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.SwingUtilities;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListDataListener;

/*
 * UIMain.java
 *
 * Created on __DATE__, __TIME__
 */
/**
 * 
 * @author __USER__
 */
public class UIMain extends javax.swing.JFrame
{
	private JScrollPane jScrollPane2;
	private JTextArea jTextArea2;
	private JScrollPane jScrollPane3;
	private JTextArea jTextArea3;
	private ArrayList<String> arr_model2;
	private JScrollPane jScrollPane4;
	private JTextArea jTextArea4;
	private JComboBox jcb_dataBase;
	private JButton jb_about;
	private JButton jb_file;

	/** Creates new form UIMain */
	public UIMain()
	{
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		GroupLayout layout = new GroupLayout((JComponent) getContentPane());
		getContentPane().setLayout(layout);
		jPanel4 = new javax.swing.JPanel();
		{
			jTabbedPane1 = new JTabbedPane();
			{
				jScrollPane1 = new JScrollPane();
				jTabbedPane1.addTab("DBMain", null, jScrollPane1, null);
				jScrollPane1.setPreferredSize(new java.awt.Dimension(451, 341));
				{
					jTextArea1 = new javax.swing.JTextArea();
					jScrollPane1.setViewportView(jTextArea1);
					jTextArea1.setColumns(20);
					jTextArea1.setRows(5);
				}
			}
		}
		{
			jb_about = new JButton();
			jb_about.setText("\u5173\u4e8e");
			jb_about.addActionListener(new ActionListener()
			{
				public void actionPerformed(ActionEvent evt)
				{
					// TODO add your code for
					// jb_about.actionPerformed
					JOptionPane.showMessageDialog(UIMain.this, "目前仅支持SQL Server,MySQL\n如有Bug，请@zyl");
				}
			});
		}
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jf_username = new javax.swing.JTextField();
		jf_password = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jf_address = new javax.swing.JTextField();
		jf_port = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jf_dbname = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		GroupLayout jPanel2Layout = new GroupLayout((JComponent) jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jLabel5 = new javax.swing.JLabel();
		jf_tablename = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jb_copy = new javax.swing.JButton();
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("oR\u6620\u5c04\u5de5\u5177");
		setResizable(false);
		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "\u6570\u636e\u5e93\u767b\u9646\u540d"));
		jLabel1.setText("\u7528\u6237\u540d");
		jLabel2.setText("\u5bc6\u7801");
		jf_username.setColumns(7);
		jf_username.setText("sa");
		jf_password.setColumns(7);
		jf_password.setText("sa");
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		{
			jb_file = new JButton();
			jb_file.setText("\u8f93\u51fa\u81f3\u6587\u4ef6...");
		}
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jf_username, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2).addGap(18, 18, 18).addComponent(jf_password, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(jf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(jf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(8, Short.MAX_VALUE)));
		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "\u6570\u636e\u5e93\u5730\u5740"));
		jLabel3.setText("\u5730\u5740");
		jLabel4.setText("\u7aef\u53e3");
		jf_address.setColumns(10);
		jf_address.setText("100.1.0.46");
		jf_address.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jf_addressActionPerformed(evt);
			}
			private void jf_addressActionPerformed(ActionEvent evt)
			{
				// TODO Auto-generated method stub
			}
		});
		jf_port.setColumns(5);
		jf_port.setText("1433");
		{
			ComboBoxModel jcb_dataBaseModel = 
					new DefaultComboBoxModel(
							new String[] { BuildTool.DATABASE_SQLSERVER, BuildTool.DATABASE_MYSQL });
			jcb_dataBase = new JComboBox();
			jcb_dataBase.setModel(jcb_dataBaseModel);
		}
		{
			arr_model2 = new ArrayList<String>();
			model2 = new jComboboxModel(arr_model2);
			jComboBox2 = new JComboBox();
			jComboBox2.setModel(model2);
		}
		jLabel6.setText("\u6570\u636e\u5e93");
		jf_dbname.setText("bookshop_case");
		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createSequentialGroup()
			.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			    .addComponent(jcb_dataBase, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			    .addComponent(jf_address, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			    .addComponent(jLabel3, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			    .addComponent(jLabel4, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			    .addComponent(jf_port, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
			.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			    .addComponent(jComboBox2, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			    .addComponent(jf_dbname, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			    .addComponent(jLabel6, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE))
			.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED));
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createSequentialGroup()
			.addGroup(jPanel3Layout.createParallelGroup()
			    .addGroup(GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
			        .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			        .addComponent(jf_dbname, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)
			        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED))
			    .addGroup(GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
			        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			        .addComponent(jf_address, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)))
			.addGroup(jPanel3Layout.createParallelGroup()
			    .addComponent(jComboBox2, GroupLayout.Alignment.LEADING, 0, 182, Short.MAX_VALUE)
			    .addGroup(GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
			        .addPreferredGap(jComboBox2, jLabel4, LayoutStyle.ComponentPlacement.INDENT)
			        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			        .addComponent(jf_port, 0, 53, Short.MAX_VALUE)
			        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			        .addComponent(jcb_dataBase, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE))));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "\u6570\u636e\u5e93\u8868\u540d"));
		{
			jb_get = new javax.swing.JButton();
			jb_get.setText("\u5237\u65b0");
			jb_get.addActionListener(new java.awt.event.ActionListener()
			{
				public void actionPerformed(java.awt.event.ActionEvent evt)
				{
					try
					{
						jb_getActionPerformed(evt);
					} catch (IOException e)
					{
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			});
		}
		jLabel5.setText("\u8868\u540d");
		jf_tablename.setColumns(10);
		jf_tablename.setText("users");
		jf_tablename.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jf_tablenameActionPerformed(evt);
			}
			private void jf_tablenameActionPerformed(ActionEvent evt)
			{
				// TODO Auto-generated method stub
			}
		});
		jButton1.setText("OK");
		jButton1.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jButton1ActionPerformed(evt);
			}
		});
		jb_copy.setText("Copy\u5168\u90e8");
		jb_copy.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jb_copyActionPerformed(evt);
			}
		});
		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createSequentialGroup()
			.addGroup(jPanel4Layout.createParallelGroup()
			    .addGroup(GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
			        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
			        .addGap(6))
			    .addComponent(jPanel1, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE))
			.addGroup(jPanel4Layout.createParallelGroup()
			    .addGroup(GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
			        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
			        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			        .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			            .addComponent(jb_copy, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			            .addComponent(jb_get, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
			            .addComponent(jb_file, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)))
			    .addGroup(GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
			        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
			        .addGap(0, 13, Short.MAX_VALUE)))
			.addContainerGap());
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createSequentialGroup()
			.addContainerGap()
			.addGroup(jPanel4Layout.createParallelGroup()
			    .addGroup(GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
			        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE)
			        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			        .addGroup(jPanel4Layout.createParallelGroup()
			            .addGroup(GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
			                .addComponent(jb_copy, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
			                .addComponent(jb_get, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
			                .addComponent(jb_file, 0, 104, Short.MAX_VALUE)
			                .addGap(6))
			            .addComponent(jButton1, GroupLayout.Alignment.LEADING, 0, 287, Short.MAX_VALUE)))
			    .addGroup(GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
			        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 367, GroupLayout.PREFERRED_SIZE)
			        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			        .addComponent(jPanel1, 0, 184, Short.MAX_VALUE))));
		layout.setVerticalGroup(layout.createSequentialGroup().addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 177, GroupLayout.PREFERRED_SIZE).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 375, GroupLayout.PREFERRED_SIZE).addComponent(jb_about, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE));
		layout.setHorizontalGroup(layout.createParallelGroup().addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup().addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 563, GroupLayout.PREFERRED_SIZE).addContainerGap(11, Short.MAX_VALUE)).addGroup(layout.createSequentialGroup().addGap(19).addGroup(layout.createParallelGroup().addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup().addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 544, GroupLayout.PREFERRED_SIZE).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)).addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup().addGap(0, 480, Short.MAX_VALUE).addComponent(jb_about, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE))).addContainerGap()));
		pack();
		this.setSize(580, 618);
		String lnfName = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
		try
		{
			javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
			SwingUtilities.updateComponentTreeUI(this);
		} catch (UnsupportedLookAndFeelException ex1)
		{
			System.err.println("Unsupported LookAndFeel: " + lnfName);
		} catch (ClassNotFoundException ex2)
		{
			System.err.println("LookAndFeel class not found: " + lnfName);
		} catch (InstantiationException ex3)
		{
			System.err.println("Could not load LookAndFeel: " + lnfName);
		} catch (IllegalAccessException ex4)
		{
			System.err.println("Cannot use LookAndFeel: " + lnfName);
		}
		setLocationRelativeTo(null);
		Properties p = new Properties();
		try
		{
			BufferedReader br = new BufferedReader(new FileReader("zyl.properties"));
			p.load(br);
			jf_tablename.setText((String) p.get("tablename"));
			jf_address.setText((String) p.get("host"));
			jf_port.setText((String) p.get("port"));
			jf_dbname.setText((String) p.get("dbname"));
			jf_username.setText((String) p.get("username"));
			jf_password.setText((String) p.get("password"));
			jcb_dataBase.setSelectedItem(p.getProperty("dbsoft"));
			br.close();
		} catch (FileNotFoundException e1)
		{
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (IOException e1)
		{
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		tool = new BuildTool(jf_address.getText(), jf_port.getText(), jf_dbname.getText(), jf_username.getText(), jf_password.getText(), (String)jcb_dataBase.getSelectedItem());
		arr_model1 = new ArrayList<String>();
		model1 = new jComboboxModel(arr_model1);
		jComboBox1.setModel(model1);
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jComboBox1, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE).addComponent(jLabel5, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE).addComponent(jf_tablename, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)).addContainerGap(20, 20));
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jf_tablename, 0, 88, Short.MAX_VALUE).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, 1, GroupLayout.PREFERRED_SIZE).addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE).addContainerGap());
		jComboBox1.addItemListener(new ItemListener()
		{
			@Override
			public void itemStateChanged(ItemEvent e)
			{
				// TODO Auto-generated method stub
				String str = (String) e.getItem();
				jf_tablename.setText(str);
			}
		});
		jComboBox2.addItemListener(new ItemListener()
		{
			@Override
			public void itemStateChanged(ItemEvent e)
			{
				// TODO Auto-generated method stub
				String str = (String) e.getItem();
				jf_dbname.setText(str);
				tool = new BuildTool(jf_address.getText(), jf_port.getText(), jf_dbname.getText(), jf_username.getText(), jf_password.getText(),(String)jcb_dataBase.getSelectedItem());
				try
				{
					refreshjComboBox1(tool);
				} catch (SQLException e1)
				{
					// TODO Auto-generated catch block
					e1.printStackTrace();
					JOptionPane.showMessageDialog(null, e1.getMessage());
				}
			}
		});
		setIconImage(new ImageIcon(this.getClass().getResource("or.png")).getImage());
		jTextArea1.addKeyListener(new KeyListener()
		{
			@Override
			public void keyTyped(KeyEvent e)
			{
				// TODO Auto-generated method stub
				e.consume();
			}
			@Override
			public void keyReleased(KeyEvent e)
			{
				// TODO Auto-generated method stub
			}
			@Override
			public void keyPressed(KeyEvent e)
			{
				// TODO Auto-generated method stub
				e.consume();
			}
		});
		this.addWindowListener(new WindowAdapter()
		{
			@Override
			public void windowClosing(WindowEvent e)
			{
				// TODO Auto-generated method stub
				Properties p = new Properties();
				p.setProperty("tablename", jf_tablename.getText());
				p.put("host", jf_address.getText());
				p.put("port", jf_port.getText());
				p.put("dbname", jf_dbname.getText());
				p.put("username", jf_username.getText());
				p.put("password", jf_password.getText());
				p.put("dbsoft", (String)jcb_dataBase.getSelectedItem());
				PrintWriter pw;
				try
				{
					pw = new PrintWriter("zyl.properties");
					p.list(pw);
					pw.close();
				} catch (FileNotFoundException e1)
				{
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				System.exit(0);
			}
			@Override
			public void windowOpened(WindowEvent e)
			{
				// TODO Auto-generated method stub
//				try
//				{
//					arr_model1 = tool.getTables();
//					arr_model2 = tool.getDatabases();
//					jComboBox2.setModel(new jComboboxModel(arr_model2));
//					jComboBox1.setModel(new jComboboxModel(arr_model1));
//				} catch (SQLException e1)
//				{
//					// TODO Auto-generated catch block
//					e1.printStackTrace();
//				} catch (ClassNotFoundException e1)
//				{
//					// TODO Auto-generated catch block
//					e1.printStackTrace();
//				}
			}
		});
		jb_file.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent evt)
			{
				UIFile u = new UIFile(UIMain.this, jf_address.getText(), jf_port.getText(), jf_dbname.getText(), jf_username.getText(), jf_password.getText(), jf_tablename.getText(), (String)jcb_dataBase.getSelectedItem());
			}
		});
		try
		{
			String dbmain = tool.buildDBMain();
			jTextArea1.setText(dbmain);
		} catch (IOException e1)
		{
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	}// </editor-fold>
		// GEN-END:initComponents
	private void jb_copyActionPerformed(java.awt.event.ActionEvent evt)
	{
		// TODO add your handling code here:
		JTextArea[] areas =
		{ jTextArea1, jTextArea2, jTextArea3, jTextArea4 };
		StringSelection stringSelection = new StringSelection(areas[jTabbedPane1.getSelectedIndex()].getText());
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null);
	}
	private void jb_getActionPerformed(java.awt.event.ActionEvent evt) throws IOException
	{
		// TODO add your handling code here:
		final BuildTool tool = new BuildTool(jf_address.getText(), jf_port.getText(), jf_dbname.getText(), jf_username.getText(), jf_password.getText(), (String)jcb_dataBase.getSelectedItem());
		try
		{
			refreshDBMain(tool);
			refreshjComboBox1(tool);
			refreshjComboBox2(tool);
		} catch (SQLException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		} catch (ClassNotFoundException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	private void refreshDBMain(BuildTool tool2) throws IOException
	{
		// TODO Auto-generated method stub
		jTextArea1.setText(tool.buildDBMain());
	}
	private void refreshjComboBox2(final BuildTool tool) throws SQLException, ClassNotFoundException
	{
		arr_model2 = tool.getDatabases();
		jComboBox2.setModel(new jComboboxModel(arr_model2));
	}
	private void refreshjComboBox1(final BuildTool tool) throws SQLException
	{
		arr_model1 = tool.getTables();
		jComboBox1.setModel(new jComboboxModel(arr_model1));
	}
	// TODO OK按钮点击
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
	{
		// TODO add your handling code here:
		BuildTool tool = new BuildTool(jf_address.getText(), jf_port.getText(), jf_dbname.getText(), jf_username.getText(), jf_password.getText(), (String)jcb_dataBase.getSelectedItem());
		try
		{
			String class_ = tool.buildClass(jf_tablename.getText());
			String dao = tool.buildDAO(jf_tablename.getText());
			String daoTest = tool.buildDAOTest(jf_tablename.getText());
			if (jScrollPane2 == null)
			{
				jScrollPane2 = new JScrollPane();
				jTabbedPane1.addTab(getClassName(class_), null, jScrollPane2, null);
				jScrollPane2.setPreferredSize(new java.awt.Dimension(451, 341));
				{
					jTextArea2 = new javax.swing.JTextArea();
					jScrollPane2.setViewportView(jTextArea2);
					jTextArea2.setColumns(20);
					jTextArea2.setRows(5);
				}
				jTextArea2.addKeyListener(new KeyListener()
				{
					@Override
					public void keyTyped(KeyEvent e)
					{
						// TODO Auto-generated method
						// stub
						e.consume();
					}
					@Override
					public void keyReleased(KeyEvent e)
					{
						// TODO Auto-generated method
						// stub
					}
					@Override
					public void keyPressed(KeyEvent e)
					{
						// TODO Auto-generated method
						// stub
						e.consume();
					}
				});
			}
			if (jScrollPane3 == null)
			{
				jScrollPane3 = new JScrollPane();
				jTabbedPane1.addTab(getClassName(dao), null, jScrollPane3, null);
				jScrollPane3.setPreferredSize(new java.awt.Dimension(451, 341));
				{
					jTextArea3 = new javax.swing.JTextArea();
					jScrollPane3.setViewportView(jTextArea3);
					jTextArea3.setColumns(20);
					jTextArea3.setRows(5);
				}
				jTextArea3.addKeyListener(new KeyListener()
				{
					@Override
					public void keyTyped(KeyEvent e)
					{
						// TODO Auto-generated method
						// stub
						e.consume();
					}
					@Override
					public void keyReleased(KeyEvent e)
					{
						// TODO Auto-generated method
						// stub
					}
					@Override
					public void keyPressed(KeyEvent e)
					{
						// TODO Auto-generated method
						// stub
						e.consume();
					}
				});
			}
			if (jScrollPane4 == null)
			{
				jScrollPane4 = new JScrollPane();
				jTabbedPane1.addTab(getClassName(daoTest), null, jScrollPane4, null);
				jScrollPane4.setPreferredSize(new java.awt.Dimension(451, 341));
				{
					jTextArea4 = new javax.swing.JTextArea();
					jScrollPane4.setViewportView(jTextArea4);
					jTextArea4.setColumns(20);
					jTextArea4.setRows(5);
				}
				jTextArea4.addKeyListener(new KeyListener()
				{
					@Override
					public void keyTyped(KeyEvent e)
					{
						// TODO Auto-generated method
						// stub
						e.consume();
					}
					@Override
					public void keyReleased(KeyEvent e)
					{
						// TODO Auto-generated method
						// stub
					}
					@Override
					public void keyPressed(KeyEvent e)
					{
						// TODO Auto-generated method
						// stub
						e.consume();
					}
				});
			}
			jTabbedPane1.setTitleAt(1, getClassName(class_));
			jTabbedPane1.setTitleAt(2, getClassName(dao));
			jTabbedPane1.setTitleAt(3, getClassName(daoTest));
			jTextArea2.setText(class_);
			jTextArea3.setText(dao);
			jTextArea4.setText(daoTest);
		} catch (ClassNotFoundException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		} catch (SQLException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		} catch (IOException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	private String getClassName(String str)
	{
		String classname = null;
		Pattern p = Pattern.compile("class \\w+");
		Matcher m = p.matcher(str);
		if (m.find())
		{
			classname = m.group().split(" ")[1];
		}
		return classname;
	}
	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt)
	{
		// TODO add your handling code here:
	}
	/**
	 * @param args
	 *                the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new UIMain().setVisible(true);
			}
		});
	}

	class jComboboxModel extends DefaultComboBoxModel
	{
		String item;
		ArrayList<String> arr;

		public jComboboxModel(ArrayList<String> arr)
		{
			// TODO Auto-generated constructor stub
			this.arr = arr;
		}
		@Override
		protected void fireContentsChanged(Object source, int index0, int index1)
		{
			// TODO Auto-generated method stub
			super.fireContentsChanged(source, index0, index1);
		}
		@Override
		public void removeListDataListener(ListDataListener l)
		{
			// TODO Auto-generated method stub
		}
		@Override
		public int getSize()
		{
			// TODO Auto-generated method stub
			return arr.size();
		}
		@Override
		public Object getElementAt(int index)
		{
			// TODO Auto-generated method stub
			return arr.get(index);
		}
		@Override
		public void addListDataListener(ListDataListener l)
		{
			// TODO Auto-generated method stub
		}
		@Override
		public void setSelectedItem(Object anItem)
		{
			// TODO Auto-generated method stub
			item = (String) anItem;
		}
		@Override
		public Object getSelectedItem()
		{
			// TODO Auto-generated method stub
			return item;
		}
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private JScrollPane jScrollPane1;
	private JComboBox jComboBox2;
	private JTabbedPane jTabbedPane1;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JButton jb_copy;
	private javax.swing.JButton jb_get;
	private javax.swing.JTextField jf_address;
	private javax.swing.JTextField jf_dbname;
	private javax.swing.JTextField jf_password;
	private javax.swing.JTextField jf_port;
	private javax.swing.JTextField jf_tablename;
	private javax.swing.JTextField jf_username;
	// End of variables declaration//GEN-END:variables
	private ArrayList<String> arr_model1;
	private DefaultComboBoxModel model1;
	private String[] items;
	private jComboboxModel model2;
	private BuildTool tool;
}